
package xx.mx.uv.contabilidad.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "contabilidadPortService", targetNamespace = "t4is.uv.mx/contabilidad", wsdlLocation = "https://contabillidad-production.up.railway.app/ws/contabilidad.wsdl")
public class ContabilidadPortService
    extends Service
{

    private final static URL CONTABILIDADPORTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONTABILIDADPORTSERVICE_EXCEPTION;
    private final static QName CONTABILIDADPORTSERVICE_QNAME = new QName("t4is.uv.mx/contabilidad", "contabilidadPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://contabillidad-production.up.railway.app/ws/contabilidad.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONTABILIDADPORTSERVICE_WSDL_LOCATION = url;
        CONTABILIDADPORTSERVICE_EXCEPTION = e;
    }

    public ContabilidadPortService() {
        super(__getWsdlLocation(), CONTABILIDADPORTSERVICE_QNAME);
    }

    public ContabilidadPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONTABILIDADPORTSERVICE_QNAME, features);
    }

    public ContabilidadPortService(URL wsdlLocation) {
        super(wsdlLocation, CONTABILIDADPORTSERVICE_QNAME);
    }

    public ContabilidadPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONTABILIDADPORTSERVICE_QNAME, features);
    }

    public ContabilidadPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContabilidadPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ContabilidadPort
     */
    @WebEndpoint(name = "contabilidadPortSoap11")
    public ContabilidadPort getContabilidadPortSoap11() {
        return super.getPort(new QName("t4is.uv.mx/contabilidad", "contabilidadPortSoap11"), ContabilidadPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContabilidadPort
     */
    @WebEndpoint(name = "contabilidadPortSoap11")
    public ContabilidadPort getContabilidadPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("t4is.uv.mx/contabilidad", "contabilidadPortSoap11"), ContabilidadPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONTABILIDADPORTSERVICE_EXCEPTION!= null) {
            throw CONTABILIDADPORTSERVICE_EXCEPTION;
        }
        return CONTABILIDADPORTSERVICE_WSDL_LOCATION;
    }

}
