
package xx.mx.uv.contabilidad.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "contabilidadPort", targetNamespace = "t4is.uv.mx/contabilidad")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ContabilidadPort {


    /**
     * 
     * @param validarPagoRequest
     * @return
     *     returns xx.mx.uv.contabilidad.wsdl.ValidarPagoResponse
     */
    @WebMethod(operationName = "ValidarPago")
    @WebResult(name = "ValidarPagoResponse", targetNamespace = "t4is.uv.mx/contabilidad", partName = "ValidarPagoResponse")
    public ValidarPagoResponse validarPago(
        @WebParam(name = "ValidarPagoRequest", targetNamespace = "t4is.uv.mx/contabilidad", partName = "ValidarPagoRequest")
        ValidarPagoRequest validarPagoRequest);

    /**
     * 
     * @param solicitarPagoRequest
     * @return
     *     returns xx.mx.uv.contabilidad.wsdl.SolicitarPagoResponse
     */
    @WebMethod(operationName = "SolicitarPago")
    @WebResult(name = "SolicitarPagoResponse", targetNamespace = "t4is.uv.mx/contabilidad", partName = "SolicitarPagoResponse")
    public SolicitarPagoResponse solicitarPago(
        @WebParam(name = "SolicitarPagoRequest", targetNamespace = "t4is.uv.mx/contabilidad", partName = "SolicitarPagoRequest")
        SolicitarPagoRequest solicitarPagoRequest);

}
